const PRODUCTS: ProductDetailItem[] = [
  {
    id: "prod-red-flag",
    name: "Red Flag",
    price: 2499,
    displayPrice: "₹2,499",
    tag: "Signature",
    color: "Blood Crimson",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/red-flag.png",
  },
  {
    id: "prod-hooked",
    name: "Hooked",
    price: 2699,
    displayPrice: "₹2,699",
    tag: "Heavyweight",
    color: "Onyx Black",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/Hooked.png",
  },
  {
    id: "prod-done-playing-blue",
    name: "Done Playing",
    price: 2799,
    displayPrice: "₹2,799",
    tag: "Washed Cut",
    color: "Cobalt Blue",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/done-playing-blue.png",
  },
  {
    id: "prod-ulterior-motive-green",
    name: "Ulterior Motive",
    price: 2799,
    displayPrice: "₹2,799",
    tag: "Limited",
    color: "Forest Green",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/Ulterior-motive-green.png",
  },
  {
    id: "prod-transcend",
    name: "Transcend",
    price: 3199,
    displayPrice: "₹3,199",
    tag: "Raw Hem",
    color: "Acid Stone",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/transcend.png",
  },
  {
    id: "prod-disaster-black",
    name: "Disaster",
    price: 2999,
    displayPrice: "₹2,999",
    tag: "Boxy Fit",
    color: "Washed Black",
    sizes: ["S", "M", "L", "XL"],
    image: "/products/disaster-black.png",
  },
];